### ISSUE TITLE
Peer review from Group61

### ISSUE THREAD

**Issue by Yuechen-Zhang603** [eeeee-cmd/US_Election#2]
**Summary**
This paper models the 2024 U.S. presidential election between Donald Trump and Kamala Harris, using polling data to predict the outcome of the election. A linear regression model is used in the paper to estimate support for each candidate based on predictors such as poll scores, sample size, state and polling regency. It highlights the importance of state-level dynamics and swing states in shaping the outcome, with Trump projected to win the election by a narrow margin despite Harris' lead in the popular vote. This study provides valuable insights into the interplay between different factors and election outcomes.

**Strong positive points**

- Explicit focus on swing states: emphasising the importance of battlefield states and state-level dynamics is a key strength.

- Model simplicity and interpretability: the linear regression model is reasonable and easy to understand for readers without a background in complex statistics.

- Comprehensive data analysis: the authors make effective use of publicly available polling data, demonstrating proficiency in data processing, cleaning and visualization.

**Critical improvements needed**

1. Data and R not cited
The raw data download from the website and R is not properly cited in the main content.

2. Lack of detailed explanation of pollster methodology
Papers should include a comprehensive analysis of the methodology of a particular pollster, but the papers submitted so far lack in-depth exploration of this area. Papers must discuss the sampling frame of the selected pollster, its recruitment methods, how it handles non-response, and the strengths and weaknesses of its methodology. Without this, the reader cannot fully understand how the quality of polling data varies depending on the methodology used by different pollsters.

3. Limited discussion of sampling trade-offs
This task requires a discussion of trade-offs in sampling methods, such as cost versus sample size or accuracy. Without addressing this issue, this paper ignores an important aspect of polling design. Explaining the potential biases introduced by different sampling methods and how they affect election predictions is critical.

4. Incomplete handling of non-response bias
Polls often struggle with non-response bias, whereby certain groups of people are less likely to respond to a survey, which can skew results. The paper should discuss how pollsters manage non-response bias, or how it can be dealt with in idealized methods.

5. Figure5 and Figure6 x-axis label is not clear
The x-axis labels in Figure5 and Figure6 are too dense and tight which is not easy to read and discern

**Suggestions for improvement:**

Choose a polling organisation, such as YouGov or Ipsos, and analyse their methodology thoroughly. Give details of the population they sample, how they deal with non-response, the sampling techniques they use, and the strengths and limitations of their methodology.

Cite R and the data at the first page or the data part in the main content

The introduction part could be little shorter

Provide an analysis of the trade-offs involved in polling methods and clarify the methods used to aggregate polling data. Explain why recent polls are given more weight than previous polls and how the credibility of the pollster or sample size is taken into account in the weighting process.

**Evaluation**

R appropriately cited: 0- Not cited in the main content
Data appropriately cited: 0-Not cited in the main content
Class paper: 1 - Yes. There is no indication that this is a class project.
LLM usage is documented: 0 - No. There is no mention of any LLM or auto-complete tools in the paper.
Title: 2 - Exceptional. The title is informative and clearly conveys the main objective of the paper.
Author, date, and repo: 2 - Yes. The GitHub repo is clearly linked, and the paper is dated.
Abstract: 3 - Exceeds expectations. The abstract is concise and clearly outlines what the paper covers, though it could include more specific results.
Introduction: 3 - Exceeds expectations. The introduction covers all the necessary details, including the broader context and the paper's objectives.
Estimand: 1 - Done. The estimand is clearly stated in terms of the projected electoral outcome.
Data: 6 - Acceptable. The data is well-explained, but there is room for improvement in describing the poll aggregation process.
Measurement: 3 - Acceptable. The measurement section is thorough, though further details on poll weighting would enhance it.
Model: 6 - Acceptable. The linear regression model is appropriate, but using more advanced models would improve the predictive accuracy.
Results: 6 - Exceeds expectations. Results are clearly presented, though additional visualizations could improve clarity.
Discussion: 6 - Exceeds expectations. The discussion covers key insights from the model and acknowledges its limitations, though more could be said about external factors.
Prose: 6 - Exceptional. The writing is clear, well-structured, and free from significant grammatical issues.
Cross-references: 1 - Yes. All figures and tables are numbered and referenced correctly.
Captions: 2 - Excellent. Figures and tables include meaningful captions.
Graphs/tables/etc.: 2 - Acceptable. The box plots are useful, but additional visualizations could enhance the overall presentation.
Idealized methodology: 6 - Acceptable. The proposed methodology is solid but could be expanded with more details.
Idealized survey: 3 - Exceeds expectations. The survey design is thoughtful, covering key demographic and voter intent questions.
Pollster methodology overview and evaluation: 6 - Acceptable. More in-depth analysis of the pollster’s reliability performance would strengthen this section.
Referencing: 4 -References are properly cited
Commits: 2-Yes
Sketches:2-Yes
Simulation:3-could be Including interactions between variables
Test:8
Parquet:1-Done
Reproducible workflow:3
Miscellaneous: 3-it discuss the situation on swing states

**Estimated overall mark**
91/126

**Any other comments:**
This paper is well written wit clear logic and shows a good understanding of election prediction techniques, but some parts, especially about model proofs and vote weighting, could have been more detailed.

**Comment by RayanAlim** [comment]
we have:
- Added more explicit focus on swing states and emphasizing battlefield states
- Expanded on the model section 
- Talked about trade-offs involved in polling methods 
-  Expanded on the pollster method using New York Times/Siena College Poll as the example
- Tightened the introduction
- Clean up figure 5 and 6
