### ISSUE TITLE
Peer Review from group 108

### ISSUE THREAD

**Issue by YizheChenUT** [eeeee-cmd/US_Election#3]
**Summary:**
The paper, Trump vs. Harris: A Data-Driven Forecast modeling the 2024 US Presidential Elections, presents a statistical model predicting the outcomes of the 2024 U.S. Presidential election, focusing on both the popular vote and the Electoral College. The analysis incorporates polling data, demographic variables, and state-level dynamics. The findings suggest that Donald Trump has a slight edge in the Electoral College, despite Kamala Harris potentially leading in the popular vote.

**Strong positive points:**
- Comprehensive use of polling and demographic data to model state-level election outcomes.
- Clear presentation of predictive models, including detailed explanations of variables and justifications for model choice.

**Critical improvements needed:**

- Graph Formatting and Presentation: Several figures are missing captions and require revisions to improve clarity. For example, the current box plots do not represent the dataset effectively. Alternative visualizations could provide a clearer picture (Figures 1-6). And, Figures 5 and 6 x axis labels are crowded
- Model Limitations: While the paper notes the use of linear regression for simplicity, it could benefit from acknowledging more potential limitations of this model choice. Consider discussing how external factors (e.g., campaign dynamics, voter turnout) could influence the model's accuracy.
- Detailed Data Cleaning: The discussion on data cleaning could be expanded. Include more specifics on the criteria used to filter out irrelevant observations and any data imputation strategies.

**Suggestions for improvement:**

- R and Data Citation: Ensure that all R packages and data sources are correctly cited and referenced both in-text and in the bibliography. Any missing references should be added.
- Polling Weighting Explanation: Clarify the process of weighing recent and high-quality polls in more detail to enhance transparency in the polling data integration.
- Variable Justification: Provide additional justification for the chosen predictor variables, especially when discussing why certain demographic factors were included while others were not.
- Methodology: Consider including more details in the appendix about alternative modeling approaches you explored but did not implement. This will give readers insight into why you chose the final model.

**Evaluation:**
R is appropriately cited: [0/1 pts]  Ensure R packages are cited correctly,.
Data are appropriately cited: 0/1 pts] Ensure data are cited
Class paper: [1/1 pts] No indication of a class paper; appropriately professional.
LLM usage is documented: [1/1 pts] 
Title: [1/2 pts] Title is informative but could be enhanced to clearly signal the model's findings.
Author, date, and repo: [2/2 pts] Author, date, and repo information is clearly presented.
Abstract: [3/4 pts] The abstract is clear, but the importance of findings could be better highlighted.
Introduction: [3/4 pts] Well-structured and self-contained introduction, but need to be  specific.
Estimand: [1/1 pts] Estimand is clearly stated.
Data: [8/10 pts] Data section is thorough but would benefit from a deeper examination of the cleaning process.
Measurement: [3/4 pts] Good explanation, but could further detail how data was transformed.
Model: [8/10 pts] Well-explained, though discussion of alternative models is limited.
Results: [8/10 pts] Results are clear but need more robust visual support.
Discussion: [8/10 pts] Comprehensive, though could further address limitations.
Prose: [4/6 pts] Generally clear but with a few noticeable typos and awkward phrasing.
Cross-references: [1/1 pts] Yes, figures are cross-referenced.
Captions: [0/2 pts] Several figures are missing captions.
Graphs/tables/etc: [2/4 pts] Some graphs are difficult to interpret and require improvements.
Idealized methodology: [8/10 pts] Solid, but the budget allocation and sample size could use more detail.
Idealized survey: [3/4 pts] Strong survey structure but could expand on the conclusion section.
Pollster methodology overview and evaluation: [0/10 pts] No Pollster methodology overview and evaluation.
Referencing: [3/4 pts] All relevant material is cited, but R packages need to be cited.
Commits: [2/2 pts] Yes, commits are meaningful.
Sketches: [2/2 pts] Sketches are present and appropriate.
Simulation: [3/4 pts] Simulation is clear and sophisticated, but should include some interaction between the variables.
Tests - simulation: [3/4 pts] Good, but additional testing would improve confidence in results.
Tests - actual: [3/4 pts] High-quality but could include more detailed results.
Parquet: [1/1 pts] Done.
Reproducible workflow: [3/4 pts] Good organization, though comments and structure could be slightly improved.
Miscellaneous: [0/3 pts] 

**Estimated overall mark:**
85 out of 126.

**Any other comments:**
Great foundation for an election forecast model with thoughtful use of polling and demographic data. The next steps could involve refining the visualizations, improving the discussion of methodology limitations, and expanding the data cleaning section for better transparency.

**Comment by RayanAlim** [comment]
We have refined the visualizations by incorporating different graph types like;
- Electoral Maps 
- Violin plots 
- Overlaying density 
- Adding tables where appropriate 
- As well as adding captions and cross-referencing to all figures and tables

We have expanded on the following sections: 
- methodology limitations
- variable justification
- model limitations

- Cited R and the Data

One comment:
-  Detailed data cleaning. Although we did clean up the data section, we did not feel it appropriate to add too much information about data cleaning to the main paper, however we have added more comments in the data cleaning script for clarity. And feel we have appropriate level of informations in the paper.
