### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by michj3** [eeeee-cmd/US_Election#4]
Summary
I am peer reviewing group 71's paper for the forecast of the US election. 

Strong positive points:
- The abstract is very clear and to the point. I like how you mention the different ways of predicting, both by popular vote and electoral college vote and the main finding of the paper is clearly stated in the abstract. Nice!
- The explanation of why Trump is predicted to win the election adds a lot to the context of the paper, stating how he has the swing states. It provides good context for readers who may not be familiar with the political state of the US, which is very helpful

Critical improvements needed:
- In the model section, instead of including a tibble, you can use kable to present a cleaner table. I also think the tibble is too long and takes up too much room, it is unnecessary. only showing the first few observations is necessary. 
- The x axis of many of the graphs need to be fixed. We cannot tell what each label is.

Suggestions for improvement:
- For the predictor variable section, I think you could use full sentences and in paragraph form, instead of in bullet point form. it seems a bit informal. 
- Discussion section could be more in depth. The only things talked about were things that the reader has already drawn conclusions on. Talk about why this modeling is importance and the context of it. 

Evaluation:
- R is appropriately cited: 1/1 
- Data are appropriately cited: 1/1
- Class paper: 1/1
- LLM usage: 1/1
- Title: 1/2 -- straightforward, but could be more creative
- author, date, repo: 2/2
- abstract: 4/4 -- concise, straight to the point
- introduction: 4/4 --  very clear and concise, providing enough information so readers understand the point of this paper
- estimand: 1/1 -- clearly stated
- data: 10/10 -- clear and each variable is stated
- measurement: 4/4 -- very thorough
- model: 8/10 -- could be presented neater
- results: 8/10 -- very thorough 
- discussion: 8/10 -- clear but could elaborate more. see comment above
- prose: 4/6 -- clear, but there are a few grammatical errors
- cross references: 1/1
- captions: 0/2 -- not done
- graphs: 1/2 -- clean up the graphs. some are very difficult to decipher
- idealized methodology: 10/10 -- very thorough and detailed. easy to follow
- idealized survey: 10/10 -- questions are laid out and easy to understand
- pollster methodology: 0/10 -- not done
- referencing: 4/4 -- all references properly cited in references
- commits: 2/2 -- clear commit messages
- sketches: 2/2 
- simulation: 4/4 -- very clear simulation script
- tests simulation: 4/4 -- high quality, thorough
- tests actual: 4/4 
- parquet: 1/1
- reproducible workflow: 4/4

Estimated overall mark:
105 out 126

**Comment by RayanAlim** [comment]
To incorporate your suggestions we have:
- Used kable to present cleaner table especially in the model section
- Only displayed the swing states rather than all 
- Fixed the x axis of many of the graphs so audience can tell what each label is.
- Expanded in the predictor variable section
- Added depth to discussion including more literature as well as recent events

Thanks for the thorough review!
