### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by tonytto** [eeeee-cmd/US_Election#5]
Summary

This paper examines prediction of 2024 U.S presidential election using polling data from ‘FiveThirtyEight’. Writers used linear model to explain their prediction and they predicted victory for Trump due to his win in swing states.

Strong positive points
- Abstract and Introduction are clear so it’s easy for reader to understand what they trying to do.
- Explanation of variables are well performed

Critical improvements needed
1. Data and R not cited
2. Labels of box plots (figure 5 and 6) are hard to see

Suggestions for improvement:
- Including justification of variables you used would be useful.
- Write little more for results and discussion would be nice. 

Evaluation
R appropriately cited: 0 Data appropriately cited: 0 Class paper: 1 LLM usage is documented: 1 Title: 2  Author, date, and repo: 2 Abstract: 4  Introduction: 3 Estimand: 1 Data: 8 Measurement: 3 Model: 8 Results: 6 Discussion: 6 Prose: 6 Cross-references: 1 Captions: 2 Graphs/tables/etc.: 2 Idealized methodology: 8 Idealized survey: 3  Pollster methodology overview and evaluation: 2 Referencing: 4 Commits: 2 Sketches: 2 Simulation: 3 Test: 8 Parquet: 1 Reproducible workflow: 3 Miscellaneous: 3

Estimated overall mark 95/126

Any other comments: This is a good first draft. Please develop little more for discussion and results section.

**Comment by RayanAlim** [comment]
Thank you for the review, to adress the points you raised we have made the following changes:
- Added depth to the justification justification of variables we used
- Expanded on our results and discussion 
- We also cited the Data and R 
- Made sure all the figures have captions and appropriate cross referencing.
- Removed the box plots to violin plots of just the candidates we care most about- Trump and Harris for better clarity of the figures
